"""Synthetic US household profile generator.

Profiles are parameterizable synthetic applicant households. They are the
"who is asking" half of every test case.

All names and addresses are generated by Faker — no real PII ever.
Income and household distributions are modeled on Census ACS microdata.
"""

from __future__ import annotations

import random
from dataclasses import dataclass, field
from functools import lru_cache
from typing import Any

from faker import Faker

from govsynth.models.enums import CitizenshipStatus

_faker = Faker("en_US")


@dataclass
class USHouseholdProfile:
    """A synthetic US household applicant profile.

    Fields map directly to ScenarioBlock fields for easy conversion.
    """

    # Core eligibility fields
    household_size: int
    monthly_gross_income: float
    state: str

    # Optional but commonly needed
    monthly_net_income: float | None = None
    liquid_assets: float = 0.0
    has_elderly_or_disabled: bool = False
    has_dependent_children: bool = False
    citizenship_status: CitizenshipStatus = CitizenshipStatus.CITIZEN

    # Persona fields (Faker-generated, never real)
    head_of_household_name: str = ""
    age_of_head: int = 35
    city: str = ""
    zip_code: str = ""

    # Income breakdown
    earned_income: float | None = None  # Portion of gross that is earned wages
    unearned_income: float = 0.0  # SSI, child support, etc.
    shelter_costs: float | None = None  # Monthly rent + utilities

    # Program-specific extras
    extra: dict[str, Any] = field(default_factory=dict)

    # Special population flags (all default to False/None — backward compatible)
    is_homeless: bool = False
    student_status: str | None = None  # None | "enrolled_half_time" | "enrolled_full_time"
    is_boarder: bool = False
    is_migrant_worker: bool = False
    has_ineligible_members: bool = False  # mixed-status HH
    ineligible_member_count: int = 0

    def __post_init__(self) -> None:
        if not self.head_of_household_name:
            self.head_of_household_name = _faker.name()
        if not self.city:
            self.city = _faker.city()
        if not self.zip_code:
            self.zip_code = _faker.zipcode()
        if self.earned_income is None:
            self.earned_income = self.monthly_gross_income

    @classmethod
    def random(
        cls,
        state: str = "VA",
        seed: int | None = None,
        strategy: str = "uniform",
    ) -> USHouseholdProfile:
        """Generate a random profile using the given strategy.

        Args:
            state: Two-letter state code.
            seed: RNG seed for reproducibility.
            strategy: 'uniform' samples freely; 'realistic' uses ACS-based weights.
        """
        rng = random.Random(seed)
        if seed is not None:
            Faker.seed(seed)

        if strategy == "realistic":
            return _build_realistic_profile(state=state, rng=rng)

        # uniform (default): national-level approximations
        hh_size = rng.choices(
            [1, 2, 3, 4, 5, 6],
            weights=[0.28, 0.34, 0.16, 0.13, 0.06, 0.03],
        )[0]

        # Monthly gross income: roughly lognormal, median ~$3,500
        gross = round(rng.lognormvariate(8.1, 0.7), -1)  # round to nearest 10
        gross = min(max(gross, 0), 15000)

        has_elderly = rng.random() < 0.15
        has_children = rng.random() < 0.35 if hh_size > 1 else False

        return cls(
            household_size=hh_size,
            monthly_gross_income=float(gross),
            state=state.upper(),
            liquid_assets=round(rng.uniform(0, 5000), -2),
            has_elderly_or_disabled=has_elderly,
            has_dependent_children=has_children,
            age_of_head=rng.randint(22, 72),
            shelter_costs=round(rng.uniform(600, 2500), -1),
        )

    @classmethod
    def at_threshold(
        cls,
        program: str,
        threshold: str,
        state: str,
        household_size: int,
        fiscal_year: int = 2026,
        offset_pct: float = 0.0,
        seed: int | None = None,
    ) -> USHouseholdProfile:
        """Build a profile at a specific policy threshold boundary.

        This factory is the core edge-case generation mechanism. It places
        the household's income or assets exactly at (or just above/below)
        a program threshold.

        Args:
            program: 'snap', 'wic', 'medicaid', etc.
            threshold: Named threshold type. See THRESHOLD_REGISTRY.
            state: Two-letter state code.
            household_size: Number of people in household.
            fiscal_year: Federal FY or calendar year for the program.
            offset_pct: How far from the threshold boundary to place the profile.
                0.0  = exactly at limit
                0.01 = 1% above limit  (should be ineligible for income tests)
               -0.01 = 1% below limit  (should be eligible)
            seed: RNG seed.

        Returns:
            USHouseholdProfile with income/assets precisely set relative to threshold.
        """
        rng = random.Random(seed)
        if seed is not None:
            Faker.seed(seed)

        if program == "snap":
            return _build_snap_threshold_profile(
                threshold=threshold,
                state=state,
                household_size=household_size,
                fiscal_year=fiscal_year,
                offset_pct=offset_pct,
                rng=rng,
            )
        elif program == "wic":
            return _build_wic_threshold_profile(
                threshold=threshold,
                state=state,
                household_size=household_size,
                fiscal_year=fiscal_year,
                offset_pct=offset_pct,
                rng=rng,
            )
        else:
            raise NotImplementedError(f"at_threshold not yet implemented for program '{program}'")

    def to_scenario_fields(self) -> dict[str, Any]:
        """Return fields suitable for populating a ScenarioBlock."""
        return {
            "household_size": self.household_size,
            "monthly_gross_income": self.monthly_gross_income,
            "monthly_net_income": self.monthly_net_income,
            "liquid_assets": self.liquid_assets,
            "state": self.state,
            "has_elderly_or_disabled": self.has_elderly_or_disabled,
            "has_dependent_children": self.has_dependent_children,
            "citizenship_status": self.citizenship_status.value,
            "additional_context": {
                "head_name": self.head_of_household_name,
                "age_of_head": self.age_of_head,
                "city": self.city,
                "earned_income": self.earned_income,
                "unearned_income": self.unearned_income,
                "shelter_costs": self.shelter_costs,
                **self.extra,
            },
        }

    def natural_language_summary(self, program: str = "snap") -> str:
        """Generate a natural language scenario description for this profile."""
        age_desc = f"{self.age_of_head}-year-old"
        hh_desc = _household_description(self.household_size, self.has_dependent_children)
        income_desc = f"${self.monthly_gross_income:,.0f}/month gross income"
        asset_desc = (
            f"${self.liquid_assets:,.0f} in savings"
            if self.liquid_assets > 0
            else "no significant savings"
        )
        elderly_desc = (
            " One household member is elderly (age 60+) or disabled."
            if self.has_elderly_or_disabled
            else ""
        )
        citizenship_desc = (
            ""
            if self.citizenship_status == CitizenshipStatus.CITIZEN
            else (
                f" {self.head_of_household_name} is a"
                f" {self.citizenship_status.value.replace('_', ' ')}."
            )
        )

        return (
            f"{self.head_of_household_name} is a {age_desc} {hh_desc}"
            f" in {self.city}, {self.state}. "
            f"Their household has {income_desc} and {asset_desc}.{elderly_desc}{citizenship_desc}"
        )


def _build_realistic_profile(state: str, rng: random.Random) -> USHouseholdProfile:
    """Build a profile sampled from Census ACS state-level distributions.

    Falls back to hardcoded national weights if no census data file exists
    (warning already emitted by CensusDataSource.load()).
    """
    from govsynth.sources.us.census import CensusDataSource

    dist = CensusDataSource(state).load()

    if dist is None:
        # No census data available -- silent fallback to national approximations
        hh_size = rng.choices([1, 2, 3, 4, 5, 6], weights=[0.28, 0.34, 0.16, 0.13, 0.06, 0.03])[0]
        gross = min(max(round(rng.lognormvariate(8.1, 0.7), -1), 0), 15000)
        return USHouseholdProfile(
            household_size=hh_size,
            monthly_gross_income=float(gross),
            state=state.upper(),
            liquid_assets=round(rng.uniform(0, 5000), -2),
            has_elderly_or_disabled=rng.random() < 0.15,
            has_dependent_children=rng.random() < 0.35 if hh_size > 1 else False,
            age_of_head=rng.randint(22, 72),
            shelter_costs=round(rng.uniform(600, 2500), -1),
        )

    # Step 3: household size from ACS weights
    hh_size = rng.choices(list(range(1, 7)), weights=dist.household_size_weights)[0]

    # Step 4: monthly gross income -- lognormal fitted to ACS income brackets
    gross = min(max(round(rng.lognormvariate(dist.income_mu, dist.income_sigma), -1), 0), 15000)

    # Step 5-6: household demographics
    # Note: pct_with_children is derived from B11003 (family households only), so it
    # overstates child presence when applied to all multi-person households. It is used
    # here as an approximation; non-family multi-person HH rarely have dependent children.
    has_children = rng.random() < dist.pct_with_children if hh_size > 1 else False
    has_elderly = rng.random() < dist.pct_elderly_or_disabled

    # Step 7: citizenship status
    roll = rng.random()
    if roll < dist.pct_citizen:
        citizenship = CitizenshipStatus.CITIZEN
    elif roll < dist.pct_citizen + dist.pct_noncitizen_eligible:
        citizenship = CitizenshipStatus.QUALIFIED_ALIEN
    else:
        citizenship = CitizenshipStatus.NON_QUALIFIED_ALIEN

    # Step 8: earned vs. unearned income split
    earned = float(gross) if rng.random() < dist.labor_force_participation_rate else 0.0
    unearned = float(gross) - earned

    # Step 9: shelter costs -- renters vs. owners
    if rng.random() < dist.pct_renter:
        sigma = dist.median_gross_rent_monthly * 0.3
        shelter = max(0.0, round(rng.normalvariate(dist.median_gross_rent_monthly, sigma), -1))
    else:
        shelter = round(rng.uniform(400, 1200), -1)

    # Step 10: age -- Normal(mu, sigma) clamped to [18, 80]
    age = max(18, min(80, round(rng.normalvariate(dist.age_mu, dist.age_sigma))))

    # dist.pct_social_security, dist.pct_ssi, dist.pct_public_assistance are available
    # for future income-source enrichment (e.g. flagging SSI/SSDI receipt on the profile).

    return USHouseholdProfile(
        household_size=hh_size,
        monthly_gross_income=float(gross),
        state=state.upper(),
        liquid_assets=round(rng.uniform(0, 3000), -2),
        has_elderly_or_disabled=has_elderly,
        has_dependent_children=has_children,
        citizenship_status=citizenship,
        earned_income=earned,
        unearned_income=unearned,
        shelter_costs=shelter,
        age_of_head=age,
    )


# ---------------------------------------------------------------------------
# Internal threshold profile builders
# ---------------------------------------------------------------------------


@lru_cache(maxsize=128)
def _household_description(size: int, has_children: bool) -> str:
    if size == 1:
        return "individual"
    if size == 2:
        return "couple" if not has_children else "single parent with one child"
    if size == 3:
        return "family of three" if not has_children else "single parent with two children"
    return f"family of {size}"


def _build_snap_threshold_profile(
    threshold: str,
    state: str,
    household_size: int,
    fiscal_year: int,
    offset_pct: float,
    rng: random.Random,
) -> USHouseholdProfile:
    """Build a SNAP-specific threshold profile."""
    from govsynth.sources.us.snap import SNAPSource, get_standard_deduction

    source = SNAPSource(fiscal_year=fiscal_year, state=state)
    t = source.thresholds()
    limits = t.by_household_size(min(household_size, 8))

    has_elderly = False
    gross_income: float
    assets: float = rng.uniform(500, 1500)

    if threshold == "gross_income_limit":
        gross_income = round(limits.gross_monthly * (1 + offset_pct), 2)
        assets = round(t.asset_limit_general * 0.5, 0) if t.asset_limit_general else 500.0

    elif threshold == "net_income_limit":
        # Back-calculate gross income that yields net income at the limit
        std_ded = get_standard_deduction(household_size)
        # net = gross - (gross * 0.20) - std = gross * 0.80 - std
        # gross = (net + std) / 0.80
        target_net = limits.net_monthly * (1 + offset_pct)
        gross_income = round((target_net + std_ded) / 0.80, 2)
        assets = round(t.asset_limit_general * 0.4, 0) if t.asset_limit_general else 400.0

    elif threshold == "asset_limit_general":
        gross_income = round(limits.gross_monthly * 0.70, 2)  # well under income limit
        asset_limit = t.asset_limit_general or 2500.0
        assets = round(asset_limit * (1 + offset_pct), 2)

    elif threshold == "asset_limit_elderly_disabled":
        has_elderly = True
        gross_income = round(limits.net_monthly * 0.80, 2)  # elderly: only net income test
        asset_limit = t.asset_limit_elderly_disabled or 3750.0
        assets = round(asset_limit * (1 + offset_pct), 2)

    else:
        raise ValueError(
            f"Unknown SNAP threshold '{threshold}'. "
            "Valid: gross_income_limit, net_income_limit, "
            "asset_limit_general, asset_limit_elderly_disabled"
        )

    # Compute net income using source's authoritative formula
    net_income = source.calculate_net_income(
        gross_income=gross_income,
        household_size=household_size,
        has_elderly_or_disabled=has_elderly,
    )

    return USHouseholdProfile(
        household_size=household_size,
        monthly_gross_income=gross_income,
        monthly_net_income=round(net_income, 2),
        liquid_assets=assets,
        state=state.upper(),
        has_elderly_or_disabled=has_elderly,
        has_dependent_children=household_size > 1 and not has_elderly,
        age_of_head=rng.randint(25, 65),
        shelter_costs=round(rng.uniform(800, 1800), -1),
        extra={
            "threshold_type": threshold,
            "offset_pct": offset_pct,
            "program": "snap",
            "fiscal_year": fiscal_year,
        },
    )


def _build_wic_threshold_profile(
    threshold: str,
    state: str,
    household_size: int,
    fiscal_year: int,
    offset_pct: float,
    rng: random.Random,
) -> USHouseholdProfile:
    """Build a WIC-specific threshold profile."""
    from govsynth.sources.us.wic import WICSource

    source = WICSource(fiscal_year=fiscal_year, state=state)
    t = source.thresholds()
    limits = t.by_household_size(min(household_size, 8))

    if threshold == "income_limit_185pct_fpl":
        gross_income = round(limits.gross_monthly * (1 + offset_pct), 2)
    else:
        raise ValueError(f"Unknown WIC threshold '{threshold}'. Valid: income_limit_185pct_fpl")

    return USHouseholdProfile(
        household_size=household_size,
        monthly_gross_income=gross_income,
        state=state.upper(),
        liquid_assets=0.0,  # No asset test for WIC
        has_dependent_children=True,
        age_of_head=rng.randint(18, 40),
        extra={
            "threshold_type": threshold,
            "offset_pct": offset_pct,
            "program": "wic",
            "fiscal_year": fiscal_year,
            "participant_category": "pregnant",
        },
    )
